// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using apiGBM.Infra;

#nullable disable

namespace apiGBM.Migrations
{
    [DbContext(typeof(ConexãoContext))]
    [Migration("20240721211651_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("apiGBM.Models.Caminhao", b =>
                {
                    b.Property<string>("cd_Placa")
                        .HasColumnType("text");

                    b.Property<int>("aa_Fabricacao")
                        .HasColumnType("integer");

                    b.Property<string>("ds_CorPrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ds_Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fk_CPFmotorista")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("qt_EixosTracao")
                        .HasColumnType("integer");

                    b.HasKey("cd_Placa");

                    b.ToTable("caminhao");
                });

            modelBuilder.Entity("apiGBM.Models.Entrega", b =>
                {
                    b.Property<Guid>("cd_Entrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ds_CargaTransportada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ds_Destino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ds_Origem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ds_StatusEntrega")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("dt_Entrega")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fk_CPFmotorista")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fk_PlacaCaminhao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("cd_Entrega");

                    b.ToTable("entrega");
                });

            modelBuilder.Entity("apiGBM.Models.Motorista", b =>
                {
                    b.Property<string>("cd_CPF")
                        .HasColumnType("text");

                    b.Property<string>("ds_CategoriaCNH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ds_Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("dt_Nascimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fk_PlacaCaminhao")
                        .HasColumnType("text");

                    b.Property<string>("nm_Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("cd_CPF");

                    b.ToTable("motorista");
                });
#pragma warning restore 612, 618
        }
    }
}
